### ISSUE TITLE
Clicking a button example causes 404

### ISSUE THREAD

**Issue by Reefersleep** [cjohansen/sasha#1]
The button examples in the live sample at https://cjohansen.github.io/?id=sasha.components.button-scenes display a 404 when clicked. 

I _assume_ that this is not the intention :) 

https://github.com/cjohansen/sasha/assets/4503878/47f4d233-2d33-499a-8368-9b39343d9df1

https://github.com/cjohansen/sasha/assets/4503878/eab2cb89-26bb-46e3-853a-0381b3ffef62

**Comment by Reefersleep** [comment]
Maybe you didn't intend for anything in particular. I read the code and saw `:href "/lul"`, recognized the vernacular ( 😊 ) and saw no html file of that name. 

Then, let me expand on my impression when I first clicked the button; the 404 gave off the sense that something in the live sample was broken. I think I would have had a better impression of the live sample, had it not seemed broken.

**Comment by cjohansen** [comment]
Good catch! I'll make sure it doesn't make a 404 😅
